name: Without container
on: push

jobs:
  test-runner:
    name: Launch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      # - uses: microsoft/playwright-github-action@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"
      - name: Install Dependencies
        run: npm i
        env:
          CI: true
      - name: Run
        run: node index
